swagger: '2.0'
info:
  version: '0.42'
  title: Test
schemes: [ http ]
basePath: "/api"
paths:
  /event_handler:
    post:
      x-mojo-to: "deployment#event"
      operationId: deployment
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        202:
          description: Accepted
          schema:
            type: object
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
        501:
          description: Not implemented
          schema:
            type: object